name: build packages

on:
  push:
    tags:
      - '*v*.*.*'

jobs:
  build:
    uses: SamirMarin/example-reusable-workflows/.github/workflows/reusable-github-package.yaml@test-branch
    with:
      working_dir: ./packages
