name: echo

on:
  push:
    tags:
      - '*v*.*.*'
    branches:
      - example-reusable-trigger

jobs:
  echo-run:
    uses: SamirMarin/example-reusable-workflows/.github/workflows/reusable-workflow-echo-repo.yaml@test-branch
