name: release packages

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Echo test
        run: |
          echo ${{ contains(github.event.pull_request.labels.*.name, 'documentation') }}
          #for label in ${{ github.event.pull_request.labels }}; do
          #  echo "current label"
          #  echo $label
          #done


