name: release packages

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Echo test
        run: |
          echo ${{ github.event.pull_request.labels }}

